export enum CartActionTypes {
    ADD_TO_CART = 'ADD_TO_CART',
    REMOVE_FROM_CART = 'REMOVE_FROM_CART',
    DELETE_FROM_CART = 'DELETE_FROM_CART',
    UPDATE_QUANTITY = 'UPDATE_QUANTITY'
}

export enum AlcoholDialogActionTypes {
    OPEN_DIALOG = 'OPEN_DIALOG',
    CLOSE_DIALOG = 'CLOSE_DIALOG'
}